/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerciciosjava.datosejercicios.grupo5.ejercicio4.ventanas;

import ejerciciosjava.datosejercicios.grupo5.ejercicio4.Alumno;
import ejerciciosjava.datosejercicios.grupo5.ejercicio4.Aula;
import ejerciciosjava.datosejercicios.grupo5.ejercicio4.Contacto;
import ejerciciosjava.datosejercicios.grupo5.ejercicio4.Direccion;
import ejerciciosjava.datosejercicios.grupo5.ejercicio4.EstadoCivil;
import ejerciciosjava.datosejercicios.grupo5.ejercicio4.Lenguaje;
import ejerciciosjava.datosejercicios.grupo5.ejercicio4.Sexo;
import ejerciciosjava.datosejercicios.grupo5.ejercicio4.TipoContacto;
import ejerciciosjava.datosejercicios.grupo5.ejercicio4.TipoEstudio;
import ejerciciosjava.datosejercicios.grupo5.ejercicio4.TiposCalle;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 * Interfaz gráfica. Encargada de mostrar los datos de cada alumno, navegar
 * entre alumnos, actualizar los datos visualizados y validar los datos antes de
 * guardarlos
 *
 * @author it-ra
 */
public class FormAlumnos extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;

	Aula miAula;				//Datos del la lista alumnos
	int alumnoSelected = 0;		//Alumno seleccionado en formulario
	int dirSelected = 0;		//Direccion seleccionada en formulario
	int contactSelected = 0;	//Contacto seleccionado en formulario
	//Modelos para ComboBox con enum y la tabla con datos alumno
	DefaultComboBoxModel estudioModel = new DefaultComboBoxModel<>(TipoEstudio.values());
	DefaultComboBoxModel callesModel = new DefaultComboBoxModel<>(TiposCalle.values());
	DefaultComboBoxModel contactosModel = new DefaultComboBoxModel<>(TipoContacto.values());

	/**
	 * Creates new form FormAlumnos
	 */
	public FormAlumnos() {
		initComponents();
		//Guarda la lista alumnos con su propietario
		miAula = new Aula("elProfesor", "IFCT0609");

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoBUTTONGROUP = new javax.swing.ButtonGroup();
        guardarBUTTONGROUP = new javax.swing.ButtonGroup();
        estadoCivilBUTTONGROUP = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codAlumTXTFIELD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        nombreCalleDirTXTFIELD = new javax.swing.JTextField();
        siguienteDirBOTON = new javax.swing.JButton();
        previaDirBOTON = new javax.swing.JButton();
        tipoCalleDirCOMBOBOX = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        numCalleDirTXTFIELD = new javax.swing.JTextField();
        pisoCalleDirTXTFIELD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        puertaDirTXTFIELD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        codPostalDirTXTFIELD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        borrarDirBOTON = new javax.swing.JButton();
        nuevaDirBOTON = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        tipoContactoCOMBOBOX = new javax.swing.JComboBox<>();
        descContactoTXTFIELD = new javax.swing.JTextField();
        previoContBOTON = new javax.swing.JButton();
        siguienteContBOTON = new javax.swing.JButton();
        borrarContBOTON = new javax.swing.JButton();
        nuevoContBOTON = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dniTXTFIELD = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nombreTXTFIELD = new javax.swing.JTextField();
        apellidosTXTFIELD = new javax.swing.JTextField();
        fechaNacDATECHOOSER = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        lengCCHECK = new javax.swing.JCheckBox();
        lengJavaCHECK = new javax.swing.JCheckBox();
        lengJSCHECK = new javax.swing.JCheckBox();
        lengCSharpCHECK = new javax.swing.JCheckBox();
        fechaIngDATECHOOSER = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        estudioCOMBOBOX = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        fotoLABEL = new javax.swing.JLabel();
        solteroRADIO = new javax.swing.JRadioButton();
        casadoRADIO = new javax.swing.JRadioButton();
        hombreRADIO = new javax.swing.JRadioButton();
        mujerRADIO = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        eliminarBOTON = new javax.swing.JButton();
        previoAlumnoBOTON = new javax.swing.JButton();
        guardarAlumnoBOTON = new javax.swing.JButton();
        nuevoBOTON = new javax.swing.JButton();
        siguienteAlumnoBOTON = new javax.swing.JButton();
        primerAlumnoBOTON = new javax.swing.JButton();
        ultimoAlumnoBOTON = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        estatusTEXTAREA = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        archivoTxtTXTAREA = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMENU = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        guardarTxtCHECKBOXMENUITEM = new javax.swing.JCheckBoxMenuItem();
        guardarDatCHECKBOXMENUITEM = new javax.swing.JCheckBoxMenuItem();
        guardarSqlCHECKBOXMENUITEM = new javax.swing.JCheckBoxMenuItem();
        editMENU = new javax.swing.JMenu();
        helpMENU = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos Aula");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jSplitPane1.setDividerLocation(450);
        jSplitPane1.setDividerSize(15);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Alumno:");

        codAlumTXTFIELD.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        codAlumTXTFIELD.setText("Cod");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Fecha nacimiento:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Direcciones"));

        nombreCalleDirTXTFIELD.setText("Brasil");

        siguienteDirBOTON.setText(">");
        siguienteDirBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteDirBOTONActionPerformed(evt);
            }
        });

        previaDirBOTON.setText("<");
        previaDirBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previaDirBOTONActionPerformed(evt);
            }
        });

        tipoCalleDirCOMBOBOX.setModel(callesModel);

        jLabel8.setText("Numero:");

        numCalleDirTXTFIELD.setText("25");

        pisoCalleDirTXTFIELD.setText("5º");

        jLabel6.setText("Piso:");

        puertaDirTXTFIELD.setText("B");

        jLabel7.setText("Puerta:");

        codPostalDirTXTFIELD.setText("36200");

        jLabel9.setText("<html>Cód.<br>Postal: </html>");

        borrarDirBOTON.setText("-");
        borrarDirBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarDirBOTONActionPerformed(evt);
            }
        });

        nuevaDirBOTON.setText("+");
        nuevaDirBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaDirBOTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tipoCalleDirCOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreCalleDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(previaDirBOTON)
                                .addGap(18, 18, 18)
                                .addComponent(borrarDirBOTON)
                                .addGap(31, 31, 31)
                                .addComponent(nuevaDirBOTON)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(siguienteDirBOTON))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numCalleDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pisoCalleDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(puertaDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codPostalDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCalleDirCOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCalleDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(numCalleDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pisoCalleDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(puertaDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codPostalDirTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previaDirBOTON)
                    .addComponent(borrarDirBOTON)
                    .addComponent(nuevaDirBOTON)
                    .addComponent(siguienteDirBOTON))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Contactos"));

        tipoContactoCOMBOBOX.setModel(contactosModel);

        descContactoTXTFIELD.setText("jTextField7");

        previoContBOTON.setText("<");
        previoContBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previoContBOTONActionPerformed(evt);
            }
        });

        siguienteContBOTON.setText(">");
        siguienteContBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteContBOTONActionPerformed(evt);
            }
        });

        borrarContBOTON.setText("-");
        borrarContBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarContBOTONActionPerformed(evt);
            }
        });

        nuevoContBOTON.setText("+");
        nuevoContBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoContBOTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previoContBOTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borrarContBOTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoContBOTON)
                .addGap(1, 1, 1)
                .addComponent(siguienteContBOTON)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descContactoTXTFIELD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(tipoContactoCOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(tipoContactoCOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descContactoTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(previoContBOTON)
                        .addComponent(borrarContBOTON))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(siguienteContBOTON)
                        .addComponent(nuevoContBOTON)))
                .addContainerGap())
        );

        jLabel10.setText("DNI:");

        dniTXTFIELD.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        dniTXTFIELD.setText("99.999.99-J");

        jLabel11.setText("<html>Fecha<br>Ingreso: </html>");

        nombreTXTFIELD.setText("nombre");

        apellidosTXTFIELD.setText("apellidos");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lengCCHECK.setText("C");

        lengJavaCHECK.setText("Java");

        lengJSCHECK.setText("JavaScript");

        lengCSharpCHECK.setText("C#");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lengJavaCHECK)
                    .addComponent(lengCCHECK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lengCSharpCHECK)
                    .addComponent(lengJSCHECK))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengCCHECK)
                    .addComponent(lengCSharpCHECK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengJavaCHECK)
                    .addComponent(lengJSCHECK))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel12.setText("<html>Estudio<br>Superior: </html>");

        estudioCOMBOBOX.setModel(estudioModel);

        fotoLABEL.setBackground(new java.awt.Color(0, 102, 153));
        fotoLABEL.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        estadoCivilBUTTONGROUP.add(solteroRADIO);
        solteroRADIO.setText("Soltero");

        estadoCivilBUTTONGROUP.add(casadoRADIO);
        casadoRADIO.setText("Casado");

        sexoBUTTONGROUP.add(hombreRADIO);
        hombreRADIO.setText("Hombre");

        sexoBUTTONGROUP.add(mujerRADIO);
        mujerRADIO.setText("Mujer");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        eliminarBOTON.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        eliminarBOTON.setText("-");
        eliminarBOTON.setMaximumSize(new java.awt.Dimension(50, 40));
        eliminarBOTON.setMinimumSize(new java.awt.Dimension(50, 40));
        eliminarBOTON.setPreferredSize(new java.awt.Dimension(50, 40));
        eliminarBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBOTONActionPerformed(evt);
            }
        });

        previoAlumnoBOTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        previoAlumnoBOTON.setText("<");
        previoAlumnoBOTON.setMaximumSize(new java.awt.Dimension(50, 40));
        previoAlumnoBOTON.setMinimumSize(new java.awt.Dimension(50, 40));
        previoAlumnoBOTON.setPreferredSize(new java.awt.Dimension(50, 40));
        previoAlumnoBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previoAlumnoBOTONActionPerformed(evt);
            }
        });

        guardarAlumnoBOTON.setText("Guardar");
        guardarAlumnoBOTON.setMaximumSize(new java.awt.Dimension(75, 40));
        guardarAlumnoBOTON.setMinimumSize(new java.awt.Dimension(75, 40));
        guardarAlumnoBOTON.setPreferredSize(new java.awt.Dimension(75, 40));
        guardarAlumnoBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAlumnoBOTONActionPerformed(evt);
            }
        });

        nuevoBOTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nuevoBOTON.setText("+");
        nuevoBOTON.setMaximumSize(new java.awt.Dimension(50, 40));
        nuevoBOTON.setMinimumSize(new java.awt.Dimension(50, 40));
        nuevoBOTON.setPreferredSize(new java.awt.Dimension(50, 40));
        nuevoBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBOTONActionPerformed(evt);
            }
        });

        siguienteAlumnoBOTON.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        siguienteAlumnoBOTON.setText(">");
        siguienteAlumnoBOTON.setMaximumSize(new java.awt.Dimension(50, 40));
        siguienteAlumnoBOTON.setMinimumSize(new java.awt.Dimension(50, 40));
        siguienteAlumnoBOTON.setPreferredSize(new java.awt.Dimension(50, 40));
        siguienteAlumnoBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteAlumnoBOTONActionPerformed(evt);
            }
        });

        primerAlumnoBOTON.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        primerAlumnoBOTON.setText("|<");
        primerAlumnoBOTON.setMaximumSize(new java.awt.Dimension(50, 40));
        primerAlumnoBOTON.setMinimumSize(new java.awt.Dimension(50, 40));
        primerAlumnoBOTON.setPreferredSize(new java.awt.Dimension(50, 40));
        primerAlumnoBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerAlumnoBOTONActionPerformed(evt);
            }
        });

        ultimoAlumnoBOTON.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ultimoAlumnoBOTON.setText(">|");
        ultimoAlumnoBOTON.setMaximumSize(new java.awt.Dimension(50, 40));
        ultimoAlumnoBOTON.setMinimumSize(new java.awt.Dimension(50, 40));
        ultimoAlumnoBOTON.setPreferredSize(new java.awt.Dimension(50, 40));
        ultimoAlumnoBOTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoAlumnoBOTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(primerAlumnoBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previoAlumnoBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarAlumnoBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(siguienteAlumnoBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ultimoAlumnoBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(guardarAlumnoBOTON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ultimoAlumnoBOTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(siguienteAlumnoBOTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevoBOTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarBOTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(previoAlumnoBOTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(primerAlumnoBOTON, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
        );

        estatusTEXTAREA.setColumns(20);
        estatusTEXTAREA.setForeground(new java.awt.Color(255, 0, 51));
        estatusTEXTAREA.setRows(5);
        jScrollPane3.setViewportView(estatusTEXTAREA);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dniTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaNacDATECHOOSER, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hombreRADIO)
                            .addComponent(mujerRADIO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casadoRADIO)
                            .addComponent(solteroRADIO)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(estudioCOMBOBOX, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fechaIngDATECHOOSER, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)))
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codAlumTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(nombreTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(apellidosTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(63, 63, 63)
                        .addComponent(fotoLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codAlumTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fotoLABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel4))
                            .addGap(1, 1, 1)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dniTXTFIELD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fechaNacDATECHOOSER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hombreRADIO, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(solteroRADIO))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(casadoRADIO)
                                .addComponent(mujerRADIO))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaIngDATECHOOSER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(estudioCOMBOBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Tabla", jPanel2);

        archivoTxtTXTAREA.setColumns(20);
        archivoTxtTXTAREA.setRows(5);
        archivoTxtTXTAREA.setAutoscrolls(false);
        jScrollPane1.setViewportView(archivoTxtTXTAREA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Archivo.txt", jPanel1);

        jSplitPane1.setRightComponent(jTabbedPane1);

        fileMENU.setText("File    ");

        jMenuItem3.setText("-------------------------------");
        fileMENU.add(jMenuItem3);

        guardarBUTTONGROUP.add(guardarTxtCHECKBOXMENUITEM);
        guardarTxtCHECKBOXMENUITEM.setSelected(true);
        guardarTxtCHECKBOXMENUITEM.setText("Guardar en .txt");
        fileMENU.add(guardarTxtCHECKBOXMENUITEM);

        guardarBUTTONGROUP.add(guardarDatCHECKBOXMENUITEM);
        guardarDatCHECKBOXMENUITEM.setText("Guardar en .dat");
        fileMENU.add(guardarDatCHECKBOXMENUITEM);

        guardarBUTTONGROUP.add(guardarSqlCHECKBOXMENUITEM);
        guardarSqlCHECKBOXMENUITEM.setText("Guardar en SQL");
        fileMENU.add(guardarSqlCHECKBOXMENUITEM);

        jMenuBar1.add(fileMENU);

        editMENU.setText("Edit    ");
        jMenuBar1.add(editMENU);

        helpMENU.setText("Help    ");
        jMenuBar1.add(helpMENU);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * Al abrir la ventana se cargan los datos del archivo de texto definido en
	 * constructor
	 *
	 * @param evt
	 */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
		miAula.loadFromTxtFile();
		actualizarTodosDatos();
    }//GEN-LAST:event_formWindowOpened

    private void siguienteAlumnoBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteAlumnoBOTONActionPerformed
		if (alumnoSelected + 1 < miAula.getListaAlumnos().size()) {
			alumnoSelected++;
			actualizarTodosDatos();
		}

    }//GEN-LAST:event_siguienteAlumnoBOTONActionPerformed

    private void previoAlumnoBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previoAlumnoBOTONActionPerformed
		if (alumnoSelected > 0) {
			alumnoSelected--;
			actualizarTodosDatos();
		}
    }//GEN-LAST:event_previoAlumnoBOTONActionPerformed

    private void previaDirBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previaDirBOTONActionPerformed
		if (dirSelected > 0) {
			dirSelected--;
			actualizaDirecciones();
		}
    }//GEN-LAST:event_previaDirBOTONActionPerformed

    private void siguienteDirBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteDirBOTONActionPerformed
		if (dirSelected + 1 < miAula.getListaAlumnos().get(alumnoSelected).getDirecciones().size()) {
			dirSelected++;
			actualizaDirecciones();
		}
    }//GEN-LAST:event_siguienteDirBOTONActionPerformed

    private void previoContBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previoContBOTONActionPerformed
		if (contactSelected > 0) {
			contactSelected--;
			actualizaContactos();
		}

    }//GEN-LAST:event_previoContBOTONActionPerformed

    private void siguienteContBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteContBOTONActionPerformed
		if (contactSelected + 1 < miAula.getListaAlumnos().get(alumnoSelected).getContactos().size()) {
			contactSelected++;
			actualizaContactos();
		}
    }//GEN-LAST:event_siguienteContBOTONActionPerformed

    private void guardarAlumnoBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAlumnoBOTONActionPerformed
		guardaCamposForm();
		for (Alumno al : miAula.getListaAlumnos()) {
			System.out.println(al.toString());
		}
		// Cantidad de alumnos en aula
		System.out.println("Cantidad alumnos en el aula: " + miAula.getListaAlumnos().size());

		estatusTEXTAREA.setText(this.miAula.saveToTxtFile());
		actualizaFormulario();
    }//GEN-LAST:event_guardarAlumnoBOTONActionPerformed

    private void eliminarBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBOTONActionPerformed
		//Confirmamos borrado
		int confirmaBorrado = JOptionPane.showOptionDialog(
				this,
				"Confirmar borrado",
				"Selector de opciones",
				JOptionPane.YES_NO_OPTION,
				JOptionPane.QUESTION_MESSAGE,
				null, // null para el icono por defecto.
				new Object[]{"Borrar", "Cancelar"},
				"Cancelar");
		if (confirmaBorrado == JOptionPane.OK_OPTION) {
			//Si no quedan alumnos saldrá aviso
			if (this.miAula.getListaAlumnos().size() == 1) {
				this.miAula.getListaAlumnos().remove(this.alumnoSelected);
				this.miAula.getListaAlumnos().add(new Alumno());
				JOptionPane.showMessageDialog(
						this, "Se han borrado todos los alumnos. Creamos uno vacio");
			} else {
				//Si no es el último, borramos alumno y cambia posición al anterior
				this.miAula.getListaAlumnos().remove(this.alumnoSelected);
				//salvo si es alumno 0, que se mantiene la posición
				if (this.alumnoSelected != 0) {
					this.alumnoSelected--;
				}
			}

			actualizaFormulario();

		} else {
			//No se borra nada y avisamos
			JOptionPane.showMessageDialog(
					this, "Cancelamos borrado");
		}


    }//GEN-LAST:event_eliminarBOTONActionPerformed

    private void nuevoBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBOTONActionPerformed
		this.miAula.getListaAlumnos().add(new Alumno());
		this.alumnoSelected = this.miAula.getListaAlumnos().size() - 1;
		actualizaFormulario();
    }//GEN-LAST:event_nuevoBOTONActionPerformed

    private void primerAlumnoBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerAlumnoBOTONActionPerformed
		this.alumnoSelected = 0;
		actualizaFormulario();
    }//GEN-LAST:event_primerAlumnoBOTONActionPerformed

    private void ultimoAlumnoBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoAlumnoBOTONActionPerformed
		this.alumnoSelected = this.miAula.getListaAlumnos().size() - 1;
		actualizaFormulario();
    }//GEN-LAST:event_ultimoAlumnoBOTONActionPerformed

    private void borrarDirBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarDirBOTONActionPerformed

    }//GEN-LAST:event_borrarDirBOTONActionPerformed

    private void nuevaDirBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaDirBOTONActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_nuevaDirBOTONActionPerformed

    private void borrarContBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarContBOTONActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_borrarContBOTONActionPerformed

    private void nuevoContBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoContBOTONActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_nuevoContBOTONActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FormAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FormAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FormAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FormAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FormAlumnos().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosTXTFIELD;
    private javax.swing.JTextArea archivoTxtTXTAREA;
    private javax.swing.JButton borrarContBOTON;
    private javax.swing.JButton borrarDirBOTON;
    private javax.swing.JRadioButton casadoRADIO;
    private javax.swing.JTextField codAlumTXTFIELD;
    private javax.swing.JTextField codPostalDirTXTFIELD;
    private javax.swing.JTextField descContactoTXTFIELD;
    private javax.swing.JTextField dniTXTFIELD;
    private javax.swing.JMenu editMENU;
    private javax.swing.JButton eliminarBOTON;
    private javax.swing.ButtonGroup estadoCivilBUTTONGROUP;
    private javax.swing.JTextArea estatusTEXTAREA;
    private javax.swing.JComboBox<String> estudioCOMBOBOX;
    private com.toedter.calendar.JDateChooser fechaIngDATECHOOSER;
    private com.toedter.calendar.JDateChooser fechaNacDATECHOOSER;
    private javax.swing.JMenu fileMENU;
    private javax.swing.JLabel fotoLABEL;
    private javax.swing.JButton guardarAlumnoBOTON;
    private javax.swing.ButtonGroup guardarBUTTONGROUP;
    private javax.swing.JCheckBoxMenuItem guardarDatCHECKBOXMENUITEM;
    private javax.swing.JCheckBoxMenuItem guardarSqlCHECKBOXMENUITEM;
    private javax.swing.JCheckBoxMenuItem guardarTxtCHECKBOXMENUITEM;
    private javax.swing.JMenu helpMENU;
    private javax.swing.JRadioButton hombreRADIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBox lengCCHECK;
    private javax.swing.JCheckBox lengCSharpCHECK;
    private javax.swing.JCheckBox lengJSCHECK;
    private javax.swing.JCheckBox lengJavaCHECK;
    private javax.swing.JRadioButton mujerRADIO;
    private javax.swing.JTextField nombreCalleDirTXTFIELD;
    private javax.swing.JTextField nombreTXTFIELD;
    private javax.swing.JButton nuevaDirBOTON;
    private javax.swing.JButton nuevoBOTON;
    private javax.swing.JButton nuevoContBOTON;
    private javax.swing.JTextField numCalleDirTXTFIELD;
    private javax.swing.JTextField pisoCalleDirTXTFIELD;
    private javax.swing.JButton previaDirBOTON;
    private javax.swing.JButton previoAlumnoBOTON;
    private javax.swing.JButton previoContBOTON;
    private javax.swing.JButton primerAlumnoBOTON;
    private javax.swing.JTextField puertaDirTXTFIELD;
    private javax.swing.ButtonGroup sexoBUTTONGROUP;
    private javax.swing.JButton siguienteAlumnoBOTON;
    private javax.swing.JButton siguienteContBOTON;
    private javax.swing.JButton siguienteDirBOTON;
    private javax.swing.JRadioButton solteroRADIO;
    private javax.swing.JComboBox<String> tipoCalleDirCOMBOBOX;
    private javax.swing.JComboBox<String> tipoContactoCOMBOBOX;
    private javax.swing.JButton ultimoAlumnoBOTON;
    // End of variables declaration//GEN-END:variables

	private void actualizarTodosDatos() {
		actualizaFormulario();
		actualizaTxtFile();
		actualizaTabla();

//		--botones
	}

	private void actualizaAlumno() {
		Alumno datosAl = this.miAula.getListaAlumnos().get(this.alumnoSelected);
		String rutaFoto = "datos\\" + this.miAula.getPropietario()
				+ "\\" + this.miAula.getAula() + "\\fotos\\";

		codAlumTXTFIELD.setText(String.valueOf(datosAl.getCodAlumno()));
		dniTXTFIELD.setText(datosAl.getDni());
		nombreTXTFIELD.setText(datosAl.getNombre());
		apellidosTXTFIELD.setText(datosAl.getApellidos());

		fechaNacDATECHOOSER.setDate(datosAl.getFechaNac().getTime());
		fechaIngDATECHOOSER.setDate(datosAl.getFechaInscr().getTime());

		this.dirSelected = datosAl.getPosDirPorDefecto();
		this.contactSelected = datosAl.getPosContactPorDefecto();

		if (datosAl.getSexo() == Sexo.HOMBRE) {
			hombreRADIO.setSelected(true);
		} else {
			mujerRADIO.setSelected(true);
		}
		if (datosAl.getEstadoCivil() == EstadoCivil.CASADO) {
			casadoRADIO.setSelected(true);
		} else {
			solteroRADIO.setSelected(true);
		}

		ImageIcon foto = new ImageIcon(rutaFoto + datosAl.getFoto());

		ImageIcon fotoAdaptada = new ImageIcon(foto.getImage().getScaledInstance(
				fotoLABEL.getWidth(),
				fotoLABEL.getHeight(),
				Image.SCALE_DEFAULT)
		);
		fotoLABEL.setIcon(fotoAdaptada);

		estudioCOMBOBOX.setSelectedItem(datosAl.getEstudioSuperior());

		lengJavaCHECK.setSelected(false);
		lengCCHECK.setSelected(false);
		lengCSharpCHECK.setSelected(false);
		lengJSCHECK.setSelected(false);
		for (Lenguaje l : datosAl.getEstudiaLenguaje()) {

			switch (l) {
				case JAVA:
					lengJavaCHECK.setSelected(true);
					break;
				case C:
					lengCCHECK.setSelected(true);
					break;
				case CSHARP:
					lengCSharpCHECK.setSelected(true);
					break;
				case JAVASCRIPT:
					lengJSCHECK.setSelected(true);
					break;
			}
		}

	}

	private void actualizaDirecciones() {
		Alumno datosAl = this.miAula.getListaAlumnos().get(this.alumnoSelected);
		tipoCalleDirCOMBOBOX.setSelectedItem(datosAl.getDirecciones().get(this.dirSelected).getTipoCalle());
		nombreCalleDirTXTFIELD.setText(datosAl.getDirecciones().get(this.dirSelected).getNombreCalle());
		numCalleDirTXTFIELD.setText(datosAl.getDirecciones().get(this.dirSelected).getNumEdif());
		pisoCalleDirTXTFIELD.setText(datosAl.getDirecciones().get(this.dirSelected).getPiso());
		puertaDirTXTFIELD.setText(datosAl.getDirecciones().get(this.dirSelected).getPuerta());
		codPostalDirTXTFIELD.setText(datosAl.getDirecciones().get(this.dirSelected).getCodigoPostal());

	}

	private void actualizaContactos() {
		Alumno datosAl = this.miAula.getListaAlumnos().get(this.alumnoSelected);
		tipoContactoCOMBOBOX.setSelectedItem(datosAl.getContactos().get(this.contactSelected).getTipo());
		descContactoTXTFIELD.setText(datosAl.getContactos().get(this.contactSelected).getDesc());

	}

	private void actualizaTxtFile() {
		Alumno datosAl = this.miAula.getListaAlumnos().get(this.alumnoSelected);
		archivoTxtTXTAREA.setText(this.miAula.readTxtFile());

	}

	private void actualizaTabla() {
		Alumno datosAl = this.miAula.getListaAlumnos().get(this.alumnoSelected);

	}

	private void guardaCamposForm() {

		//Alumno seleccionado actualmente
		Alumno datosAl = this.miAula.getListaAlumnos().get(this.alumnoSelected);

		//Guardamos datos de los campos en ese alumno
		//Datos alumno en general
		datosAl.setDni(dniTXTFIELD.getText());
		datosAl.setNombre(nombreTXTFIELD.getText());
		datosAl.setApellidos(apellidosTXTFIELD.getText());
		datosAl.setFechaNac(fechaNacDATECHOOSER.getCalendar());
		datosAl.setFechaInscr(fechaIngDATECHOOSER.getCalendar());

		if (hombreRADIO.isSelected()) {
			datosAl.setSexo(Sexo.HOMBRE);
		} else {
			datosAl.setSexo(Sexo.MUJER);
		}

		if (solteroRADIO.isSelected()) {
			datosAl.setEstadoCivil(EstadoCivil.SOLTERO);
		} else {
			datosAl.setEstadoCivil(EstadoCivil.CASADO);
		}
		datosAl.setEstudioSuperior((TipoEstudio) estudioCOMBOBOX.getSelectedItem());

		//lista lenguajes
		ArrayList<Lenguaje> newlenguaje = new ArrayList<>();
		JCheckBox[] listaLeng = new JCheckBox[]{lengCCHECK, lengCSharpCHECK, lengJavaCHECK, lengJSCHECK};

		for (JCheckBox lcheck : listaLeng) {
			if (lcheck.isSelected()) {
				switch (lcheck.getText()) {
					case "C":
						newlenguaje.add(Lenguaje.C);
						break;
					case "C#":
						newlenguaje.add(Lenguaje.CSHARP);
						break;
					case "Java":
						newlenguaje.add(Lenguaje.JAVA);
						break;
					case "JavaScript":
						newlenguaje.add(Lenguaje.JAVASCRIPT);
						break;
				}
			}
		}

		datosAl.setEstudiaLenguaje(newlenguaje);

		//Datos direccion
		Direccion datosDir = datosAl.getDirecciones().get(this.dirSelected);
		datosDir.setTipoCalle((TiposCalle) tipoCalleDirCOMBOBOX.getSelectedItem());
		datosDir.setNumEdif(numCalleDirTXTFIELD.getText());
		datosDir.setPiso(pisoCalleDirTXTFIELD.getText());
		datosDir.setPuerta(puertaDirTXTFIELD.getText());
		datosDir.setCodigoPostal(codPostalDirTXTFIELD.getText());

		//Datos contacto
		Contacto datosContacto = datosAl.getContactos().get(this.contactSelected);
		datosContacto.setTipo((TipoContacto) tipoContactoCOMBOBOX.getSelectedItem());
		datosContacto.setDesc(descContactoTXTFIELD.getText());

	}

	private void actualizaFormulario() {
		actualizaAlumno();
		actualizaDirecciones();
		actualizaContactos();
	}
}
